export class Vaccancies {
    vaccancy_id: string = '';
    vaccancy_ref_number: string = '';
    vaccancy_date: string = '';
    vaccancy_client: string = '';
    vaccancy_business_group: string = '';
    vaccancy_shift_type: string = '';
    vaccancy_job: string = '';
    vaccancy_break_time: string = '';
    vaccancy_space: string = '';
    vaccancy_location: string = '';
    vaccancy_details: string = '';
    vaccancy_created_time: string = '';
    vaccancy_updated_time: string = '';
    vaccancy_created_by: string = '';
    vaccancy_updated_by: string = '';
    vaccancy_active: string = '';
  }
  export class VaccanciesSearch {
    vaccancy_id: string = '';
    vaccancy_ref_number: string = '';
    vaccancy_date: string = '';
    vaccancy_client: string = '';
    vaccancy_business_group: string = '';
    vaccancy_shift_type: string = '';
    vaccancy_job: string = '';
    vaccancy_break_time: string = '';
    vaccancy_space: string = '';
    vaccancy_location: string = '';
    vaccancy_details: string = '';
    vaccancy_created_time: string = '';
    vaccancy_updated_time: string = '';
    vaccancy_created_by: string = '';
    vaccancy_updated_by: string = '';
    vaccancy_active: string = '';
  }